name: behresp-dev
dependencies:
- python >=3.6.5,<3.7
- numpy >=1.12.1
- pandas >=0.22.0
- git
- pip
  - git+https://github.com/open-source-economics/Tax-Calculator.git@master"
- pytest
- pytest-pep8
- pytest-xdist
- pyyaml
- pycodestyle
- pylint
- coverage
