package:
  name: behresp
  version: 0.0.0

requirements:
  build:
    - python
    - "taxcalc>=1.0"

  run:
    - python
    - "taxcalc>=1.0"

test:
  imports:
    - behresp

about:
  home: https://github.com/PSLmodels/Behavioral-Response
