package:
  name: behresp
  version: 0.0.0

requirements:
  build:
    - python >=3.6.5,<3.7
    - numpy >=1.12.1
    - pandas >=0.22.0
    - taxcalc >=0.22.1

  run:
    - python >=3.6.5,<3.7
    - numpy >=1.12.1
    - pandas >=0.22.0
    - taxcalc >=0.22.1

test:
  imports:
    - behresp

about:
  home: https://github.com/open-source-economics/Behavioral-Response
