package:
  name: behresp
  version: 0.0.0

requirements:
  build:
    - taxcalc

  run:
    - taxcalc

test:
  imports:
    - behresp

about:
  home: https://github.com/open-source-economics/Behavioral-Response
